ff_meters: ff_meters_LookAndFeelMethods.h File Reference
ff_meters_LookAndFeelMethods.h File Reference
Functions
void setupDefaultMeterColours () override
void updateMeterGradients () override
juce::Rectangle< float > getMeterInnerBounds (const juce::Rectangle< float > bounds, const foleys::LevelMeter::MeterFlags meterType) const override
juce::Rectangle< float > getMeterBounds (const juce::Rectangle< float > bounds, const foleys::LevelMeter::MeterFlags meterType, const int numChannels, const int channel) const override
juce::Rectangle< float > getMeterBarBounds (const juce::Rectangle< float > bounds, const foleys::LevelMeter::MeterFlags meterType) const override
Override this callback to define the placement of the actual meter bar.
juce::Rectangle< float > getMeterTickmarksBounds (const juce::Rectangle< float > bounds, const foleys::LevelMeter::MeterFlags meterType) const override
Override this callback to define the placement of the tickmarks.
juce::Rectangle< float > getMeterClipIndicatorBounds (const juce::Rectangle< float > bounds, const foleys::LevelMeter::MeterFlags meterType) const override
Override this callback to define the placement of the clip indicator light.
juce::Rectangle< float > getMeterMaxNumberBounds (const juce::Rectangle< float > bounds, const foleys::LevelMeter::MeterFlags meterType) const override
Override this callback to define the placement of the max level.
juce::Rectangle< float > drawBackground (juce::Graphics &g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds) override
void drawMeterBars (juce::Graphics &g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds, const foleys::LevelMeterSource *source, const int fixedNumChannels=-1, const int selectedChannel=-1) override
void drawMeterBarsBackground (juce::Graphics &g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds, const int numChannels, const int fixedNumChannels) override
void drawMeterChannel (juce::Graphics &g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds, const foleys::LevelMeterSource *source, const int selectedChannel) override
void drawMeterChannelBackground (juce::Graphics &g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds) override
void drawMeterBar (juce::Graphics &g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds, const float rms, const float peak) override
void drawMeterReduction (juce::Graphics &g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds, const float reduction) override
void drawMeterBarBackground (juce::Graphics &g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds) override
void drawTickMarks (juce::Graphics &g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds) override
void drawClipIndicator (juce::Graphics &g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds, const bool hasClipped) override
void drawClipIndicatorBackground (juce::Graphics &g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds) override
void drawMaxNumber (juce::Graphics &g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds, const float maxGain) override
void drawMaxNumberBackground (juce::Graphics &g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds) override
int hitTestClipIndicator (const juce::Point< int > position, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds, const foleys::LevelMeterSource *source) const override
int hitTestMaxNumber (const juce::Point< int > position, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds, const foleys::LevelMeterSource *source) const override
Variables
juce::ColourGradient horizontalGradient
juce::ColourGradient verticalGradient
Function Documentation
void setupDefaultMeterColours () override
References foleys::LevelMeter::lmBackgroundClipColour, foleys::LevelMeter::lmBackgroundColour, foleys::LevelMeter::lmMeterBackgroundColour, foleys::LevelMeter::lmMeterForegroundColour, foleys::LevelMeter::lmMeterGradientLowColour, foleys::LevelMeter::lmMeterGradientMaxColour, foleys::LevelMeter::lmMeterGradientMidColour, foleys::LevelMeter::lmMeterMaxNormalColour, foleys::LevelMeter::lmMeterMaxOverColour, foleys::LevelMeter::lmMeterMaxWarnColour, foleys::LevelMeter::lmMeterOutlineColour, foleys::LevelMeter::lmMeterReductionColour, foleys::LevelMeter::lmOutlineColour, foleys::LevelMeter::lmTextClipColour, foleys::LevelMeter::lmTextColour, foleys::LevelMeter::lmTextDeactiveColour, and foleys::LevelMeter::lmTicksColour.
void updateMeterGradients () override
References horizontalGradient, and verticalGradient.
juce::Rectangle<float> getMeterInnerBounds (const juce::Rectangle< float > bounds, const foleys::LevelMeter::MeterFlags meterType) const override
References foleys::LevelMeter::HasBorder.
Referenced by drawMeterBars(), and drawMeterBarsBackground().
juce::Rectangle<float> getMeterBounds (const juce::Rectangle< float > bounds, const foleys::LevelMeter::MeterFlags meterType, const int numChannels, const int channel) const override
References foleys::LevelMeter::Horizontal, and foleys::LevelMeter::SingleChannel.
Referenced by drawMeterBars(), drawMeterBarsBackground(), hitTestClipIndicator(), and hitTestMaxNumber().
juce::Rectangle<float> getMeterBarBounds (const juce::Rectangle< float > bounds, const foleys::LevelMeter::MeterFlags meterType) const override
Override this callback to define the placement of the actual meter bar.
References foleys::LevelMeter::Horizontal, foleys::LevelMeter::MaxNumber, foleys::LevelMeter::Minimal, and foleys::LevelMeter::Vintage.
Referenced by drawMeterBars(), drawMeterBarsBackground(), drawMeterChannel(), drawMeterChannelBackground(), and getMeterTickmarksBounds().
juce::Rectangle<float> getMeterTickmarksBounds (const juce::Rectangle< float > bounds, const foleys::LevelMeter::MeterFlags meterType) const override
Override this callback to define the placement of the tickmarks.
To disable this feature return an empty rectangle.
References getMeterBarBounds(), foleys::LevelMeter::Horizontal, foleys::LevelMeter::Minimal, and foleys::LevelMeter::Vintage.
Referenced by drawMeterBars(), drawMeterBarsBackground(), and drawMeterChannelBackground().
juce::Rectangle<float> getMeterClipIndicatorBounds (const juce::Rectangle< float > bounds, const foleys::LevelMeter::MeterFlags meterType) const override
Override this callback to define the placement of the clip indicator light.
To disable this feature return an empty rectangle.
References foleys::LevelMeter::Horizontal, foleys::LevelMeter::Minimal, and foleys::LevelMeter::Vintage.
Referenced by drawMeterBars(), drawMeterBarsBackground(), drawMeterChannel(), drawMeterChannelBackground(), and hitTestClipIndicator().
juce::Rectangle<float> getMeterMaxNumberBounds (const juce::Rectangle< float > bounds, const foleys::LevelMeter::MeterFlags meterType) const override
Override this callback to define the placement of the max level.
To disable this feature return an empty rectangle.
References foleys::LevelMeter::Horizontal, foleys::LevelMeter::MaxNumber, foleys::LevelMeter::Minimal, and foleys::LevelMeter::Vintage.
Referenced by drawMeterBars(), drawMeterChannel(), drawMeterChannelBackground(), and hitTestMaxNumber().
juce::Rectangle<float> drawBackground (juce::Graphics & g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds) override
References foleys::LevelMeter::HasBorder, foleys::LevelMeter::lmBackgroundColour, and foleys::LevelMeter::lmOutlineColour.
void drawMeterBars (juce::Graphics & g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds, const foleys::LevelMeterSource * source, const int fixedNumChannels = -1, const int selectedChannel = -1) override
References drawClipIndicator(), drawMaxNumber(), drawMeterBar(), drawMeterChannel(), drawMeterReduction(), drawTickMarks(), foleys::LevelMeterSource::getClipFlag(), foleys::LevelMeterSource::getMaxLevel(), foleys::LevelMeterSource::getMaxOverallLevel(), getMeterBarBounds(), getMeterBounds(), getMeterClipIndicatorBounds(), getMeterInnerBounds(), getMeterMaxNumberBounds(), getMeterTickmarksBounds(), foleys::LevelMeterSource::getNumChannels(), foleys::LevelMeterSource::getReductionLevel(), foleys::LevelMeterSource::getRMSLevel(), foleys::LevelMeter::Horizontal, foleys::LevelMeter::Minimal, and foleys::LevelMeter::SingleChannel.
void drawMeterBarsBackground (juce::Graphics & g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds, const int numChannels, const int fixedNumChannels) override
References drawClipIndicatorBackground(), drawMeterBarBackground(), drawMeterChannelBackground(), drawTickMarks(), getMeterBarBounds(), getMeterBounds(), getMeterClipIndicatorBounds(), getMeterInnerBounds(), getMeterTickmarksBounds(), foleys::LevelMeter::Horizontal, foleys::LevelMeter::Minimal, and foleys::LevelMeter::SingleChannel.
void drawMeterChannel (juce::Graphics & g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds, const foleys::LevelMeterSource * source, const int selectedChannel) override
References drawClipIndicator(), drawMaxNumber(), drawMeterBar(), drawMeterReduction(), foleys::LevelMeterSource::getClipFlag(), foleys::LevelMeterSource::getMaxLevel(), foleys::LevelMeterSource::getMaxOverallLevel(), getMeterBarBounds(), getMeterClipIndicatorBounds(), getMeterMaxNumberBounds(), foleys::LevelMeterSource::getReductionLevel(), foleys::LevelMeterSource::getRMSLevel(), foleys::LevelMeter::Horizontal, and foleys::LevelMeter::Reduction.
Referenced by drawMeterBars().
void drawMeterChannelBackground (juce::Graphics & g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds) override
References drawClipIndicatorBackground(), drawMaxNumberBackground(), drawMeterBarBackground(), drawTickMarks(), getMeterBarBounds(), getMeterClipIndicatorBounds(), getMeterMaxNumberBounds(), and getMeterTickmarksBounds().
Referenced by drawMeterBarsBackground().
void drawMeterBar (juce::Graphics & g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds, const float rms, const float peak) override
References foleys::LevelMeter::Horizontal, horizontalGradient, foleys::LevelMeter::lmMeterGradientLowColour, foleys::LevelMeter::lmMeterGradientMaxColour, foleys::LevelMeter::lmMeterGradientMidColour, foleys::LevelMeter::lmMeterMaxNormalColour, foleys::LevelMeter::lmMeterMaxOverColour, foleys::LevelMeter::lmMeterMaxWarnColour, foleys::LevelMeter::lmMeterReductionColour, foleys::LevelMeter::Reduction, verticalGradient, and foleys::LevelMeter::Vintage.
Referenced by drawMeterBars(), and drawMeterChannel().
void drawMeterReduction (juce::Graphics & g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds, const float reduction) override
References foleys::LevelMeter::Horizontal, and foleys::LevelMeter::lmMeterReductionColour.
Referenced by drawMeterBars(), and drawMeterChannel().
void drawMeterBarBackground (juce::Graphics & g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds) override
References foleys::LevelMeter::lmMeterBackgroundColour, and foleys::LevelMeter::lmMeterOutlineColour.
Referenced by drawMeterBarsBackground(), and drawMeterChannelBackground().
void drawTickMarks (juce::Graphics & g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds) override
References foleys::LevelMeter::Horizontal, foleys::LevelMeter::lmTicksColour, foleys::LevelMeter::Minimal, foleys::LevelMeter::Reduction, and foleys::LevelMeter::Vintage.
Referenced by drawMeterBars(), drawMeterBarsBackground(), and drawMeterChannelBackground().
void drawClipIndicator (juce::Graphics & g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds, const bool hasClipped) override
References foleys::LevelMeter::lmBackgroundClipColour, foleys::LevelMeter::lmMeterBackgroundColour, and foleys::LevelMeter::lmMeterOutlineColour.
Referenced by drawMeterBars(), and drawMeterChannel().
void drawClipIndicatorBackground (juce::Graphics & g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds) override
References foleys::LevelMeter::lmMeterBackgroundColour, and foleys::LevelMeter::lmMeterOutlineColour.
Referenced by drawMeterBarsBackground(), and drawMeterChannelBackground().
void drawMaxNumber (juce::Graphics & g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds, const float maxGain) override
References foleys::LevelMeter::lmMeterBackgroundColour, foleys::LevelMeter::lmMeterOutlineColour, foleys::LevelMeter::lmTextClipColour, and foleys::LevelMeter::lmTextColour.
Referenced by drawMeterBars(), and drawMeterChannel().
void drawMaxNumberBackground (juce::Graphics & g, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds) override
References foleys::LevelMeter::lmMeterBackgroundColour.
Referenced by drawMeterChannelBackground().
int hitTestClipIndicator (const juce::Point< int > position, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds, const foleys::LevelMeterSource * source) const override
References getMeterBounds(), getMeterClipIndicatorBounds(), and foleys::LevelMeterSource::getNumChannels().
int hitTestMaxNumber (const juce::Point< int > position, const foleys::LevelMeter::MeterFlags meterType, const juce::Rectangle< float > bounds, const foleys::LevelMeterSource * source) const override
References getMeterBounds(), getMeterMaxNumberBounds(), and foleys::LevelMeterSource::getNumChannels().
Variable Documentation
juce::ColourGradient horizontalGradient
Referenced by drawMeterBar(), and updateMeterGradients().
juce::ColourGradient verticalGradient
Referenced by drawMeterBar(), and updateMeterGradients().